# Generated by Django 4.1.3 on 2023-12-12 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OoenAIAPI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("input_message", models.CharField(blank=True, max_length=500)),
                ("add_message", models.CharField(blank=True, max_length=200)),
                (
                    "output_message",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "openAIへのリクエスト",
                "verbose_name_plural": "openAIへのリクエスト",
                "db_table": "openai_api",
                "ordering": ["create_at"],
            },
        ),
    ]
